M48
; DRILL file {KiCad 7.0.10-7.0.10~ubuntu22.04.1} date 2024年03月09日 00時22分00秒
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-09T00:22:00+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10-7.0.10~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X4.4626Y-3.8254
X4.6902Y-3.8254
M30
